### ISSUE TITLE
Recommended pattern for bundling a plugin into an Operator

### ISSUE THREAD

**Issue by RyanMillerC** [openshift/console-plugin-template#20]
Is there a recommended pattern to bundle a dynamic console plugin into a Go-based operator?

**Comment by spadgett** [comment]
We don't have an example for this today, although it's something we should look at adding since operators are a common way to deliver plugins.

If your operator already creates a service on the cluster, it's possible to use `http.FileServer` to serve the static plugin assets. Otherwise, you could add a sidecar container using any HTTP server like nginx or caddy. If your operator adds an `console.openshift.io/plugins` annotation to its CSV, console will prompt to enable the plugin on operator install. There's an example of the annotation in the enhancement here: https://github.com/openshift/enhancements/blob/master/enhancements/console/dynamic-plugins.md#delivering-plugins

Hope this helps.

cc @jhadvig @alimobrem

**Comment by RyanMillerC** [comment]
Thanks @spadgett, this helps! I'm close but not 100% there yet. If I can get it working I will gladly contribute an example using an Operator. 😃

I went the Nginx route and have generated a container image for my console plugin. In my operator's [./config/manifests/bases/](https://github.com/RyanMillerC/cat-facts-operator/tree/2640eb05ed0d6c7e395e46f67de042f359e3cb44/config/manifests/bases) directory I've included a Deployment (using the nginx image), Service, and ConsolePlugin. When I run `make bundle`, only the Deployment and Service are generated under [./bundle/manifests](https://github.com/RyanMillerC/cat-facts-operator/tree/2640eb05ed0d6c7e395e46f67de042f359e3cb44/bundle/manifests).

If I deploy the bundle (without ConsolePlugin), manually add the ConsolePlugin, and enable it, everything works great! I need to figure out why `make bundle` isn't including that manifest... This could be simply my lack of knowledge around the Operator SDK.

Another question I have is around namespaces. At the moment I have hardcoded the namespace in my ConsolePlugin. If someone installs the operator into a different namespace, the ConsolePlugin won't match. Is there a way around that? 

```yaml
# Example spec from my ConsolePlugin
spec:
  service:
    name: cat-facts-console-plugin
    namespace: cat-facts-operator
```

**Comment by spadgett** [comment]
@RyanMillerC Oh nice! Yes, this was definitely needed. I think we can link out to your personal GitHub repo for now and then update the link if we can move it somewhere better, maybe the `openshift` org? Have you talked to the OLM team about making it a sample?

As an aside, we've discussed creating a hello world operator for OpenShift console CI tests... We might consider using this instead, and it would let us test enabling plugins during operator install flows. @jhadvig @jcaianirh FYI

@alimobrem FYI

**Comment by RyanMillerC** [comment]
I was told redhat-cop is not a good place for example code. I'm open to moving the repo wherever makes the most sense. It would be awesome if I could still be a repo owner in the new location. I'm working on implementing a console plugin for the [patterns operator](https://github.com/hybrid-cloud-patterns/patterns-operator). There's some things I'm doing there that I would like to copy over to cat facts when I have time.

In the meantime I will open a PR to add links for both my example and the service mesh plugin.

I haven't talked to the OLM team but I'm open to talking with them. Do you have a point of contact on their team?

Thanks! 😃
